
import type { Target } from './types';

export const MOCK_TARGETS: Target[] = [
  { id: 1, name: 'Alice Johnson', company: 'Innovate Inc.', position: 'Senior Project Manager' },
  { id: 2, name: 'Bob Williams', company: 'Future Solutions', position: 'Lead Developer' },
  { id: 3, name: 'Charlie Brown', company: 'Data Dynamics', position: 'Data Analyst' },
  { id: 4, name: 'Diana Miller', company: 'QuantumLeap Co.', position: 'Marketing Director' },
  { id: 5, name: 'Ethan Davis', company: 'Innovate Inc.', position: 'Financial Controller' },
  { id: 6, name: 'Fiona Garcia', company: 'Future Solutions', position: 'HR Manager' },
  { id: 7, name: 'George Rodriguez', company: 'Data Dynamics', position: 'Systems Administrator' },
  { id: 8, name: 'Hannah Martinez', company: 'QuantumLeap Co.', position: 'Sales Executive' },
  { id: 9, name: 'Ian Hernandez', company: 'Innovate Inc.', position: 'Junior Developer' },
  { id: 10, name: 'Jane Lopez', company: 'Future Solutions', position: 'UX Designer' },
  { id: 11, name: 'Kevin Gonzalez', company: 'Data Dynamics', position: 'Business Intelligence Analyst' },
  { id: 12, name: 'Laura Wilson', company: 'QuantumLeap Co.', position: 'Operations Chief' },
  { id: 13, name: 'Mason Anderson', company: 'Innovate Inc.', position: 'Product Owner' },
  { id: 14, name: 'Nora Thomas', company: 'Future Solutions', position: 'QA Engineer' },
  { id: 15, name: 'Oscar Taylor', company: 'Data Dynamics', position: 'Database Manager' },
  { id: 16, name: 'Penelope Moore', company: 'QuantumLeap Co.', position: 'Content Strategist' },
  { id: 17, name: 'Quinn Jackson', company: 'Innovate Inc.', position: 'DevOps Engineer' },
  { id: 18, name: 'Rachel White', company: 'Future Solutions', position: 'Scrum Master' },
  { id: 19, name: 'Samuel Harris', company: 'Data Dynamics', position: 'Cloud Engineer' },
  { id: 20, name: 'Tina Clark', company: 'QuantumLeap Co.', position: 'PR Specialist' },
  { id: 21, name: 'Ulysses Lewis', company: 'Innovate Inc.', position: 'Senior Accountant' },
  { id: 22, name: 'Violet Robinson', company: 'Future Solutions', position: 'Frontend Developer' },
  { id: 23, name: 'Walter Walker', company: 'Data Dynamics', position: 'Network Security' },
  { id: 24, name: 'Xena Perez', company: 'QuantumLeap Co.', position: 'Social Media Manager' },
  { id: 25, name: 'Yusuf Hall', company: 'Innovate Inc.', position: 'Mobile Developer' },
  { id: 26, name: 'Zoe Young', company: 'Future Solutions', position: 'IT Support' },
  { id: 27, name: 'Adam Allen', company: 'Data Dynamics', position: 'Machine Learning Engineer' },
  { id: 28, name: 'Bella King', company: 'QuantumLeap Co.', position: 'Graphic Designer' },
  { id: 29, name: 'Caleb Wright', company: 'Innovate Inc.', position: 'Legal Counsel' },
  { id: 30, name: 'Daisy Scott', company: 'Future Solutions', position: 'Recruitment Specialist' },
  { id: 31, name: 'David Green', company: 'Synergy Systems', position: 'Chief Technology Officer' },
  { id: 32, name: 'Emily White', company: 'Apex Innovations', position: 'Product Manager' },
  { id: 33, name: 'Frank Black', company: 'Stellar Solutions', position: 'Lead UI/UX Designer' },
  { id: 34, name: 'Grace Hall', company: 'Nexus Corp', position: 'Head of Operations' },
  { id: 35, name: 'Henry King', company: 'Synergy Systems', position: 'Senior Backend Engineer' },
  { id: 36, name: 'Isla Scott', company: 'Apex Innovations', position: 'Digital Marketing Specialist' },
  { id: 37, name: 'Jack Adams', company: 'Stellar Solutions', position: 'Customer Success Manager' },
  { id: 38, name: 'Kate Baker', company: 'Nexus Corp', position: 'Financial Analyst' },
  { id: 39, name: 'Leo Carter', company: 'Synergy Systems', position: 'IT Security Specialist' },
  { id: 40, name: 'Mia Davis', company: 'Apex Innovations', position: 'Content Creator' },
  { id: 41, name: 'Noah Evans', company: 'Stellar Solutions', position: 'Mobile App Developer' },
  { id: 42, name: 'Olivia Ford', company: 'Nexus Corp', position: 'Legal Advisor' },
  { id: 43, name: 'Paul Garcia', company: 'Synergy Systems', position: 'Data Scientist' },
  { id: 44, name: 'Quinn Harris', company: 'Apex Innovations', position: 'QA Lead' },
  { id: 45, name: 'Ruby Jackson', company: 'Stellar Solutions', position: 'Brand Manager' },
  { id: 46, name: 'Sam Kelly', company: 'Nexus Corp', position: 'Cloud Solutions Architect' },
  { id: 47, name: 'Tara Lewis', company: 'Synergy Systems', position: 'Human Resources Generalist' },
  { id: 48, name: 'Victor Martin', company: 'Apex Innovations', position: 'Business Development Manager' },
  { id: 49, name: 'Willow Nelson', company: 'Stellar Solutions', position: 'Supply Chain Coordinator' },
  { id: 50, name: 'Xavier Ortiz', company: 'Nexus Corp', position: 'DevOps Manager' },
  { id: 51, name: 'Yara Perez', company: 'Innovate Inc.', position: 'Senior Frontend Developer' },
  { id: 52, name: 'Zane Reed', company: 'Future Solutions', position: 'Systems Analyst' },
  { id: 53, name: 'Ava Roberts', company: 'Data Dynamics', position: 'Database Administrator' },
  { id: 54, name: 'Ben Stewart', company: 'QuantumLeap Co.', position: 'AI Researcher' },
  { id: 55, name: 'Chloe Turner', company: 'Innovate Inc.', position: 'Technical Writer' },
  { id: 56, name: 'Daniel Wood', company: 'Future Solutions', position: 'Network Engineer' },
  { id: 57, name: 'Ella Hughes', company: 'Data Dynamics', position: 'BI Developer' },
  { id: 58, name: 'Finn Morris', company: 'QuantumLeap Co.', position: 'Chief Financial Officer' },
  { id: 59, name: 'Gia Bell', company: 'Synergy Systems', position: 'Compliance Officer' },
  { id: 60, name: 'Hugo Cook', company: 'Apex Innovations', position: 'Partnership Manager' },
  { id: 61, name: 'Ivy Gray', company: 'Stellar Solutions', position: 'Public Relations Manager' },
  { id: 62, name: 'Jude Howard', company: 'Nexus Corp', position: 'Infrastructure Engineer' },
  { id: 63, name: 'Kira James', company: 'Synergy Systems', position: 'Scrum Master' },
  { id: 64, name: 'Liam King', company: 'Apex Innovations', position: 'Sales Director' },
  { id: 65, name: 'Maya Long', company: 'Stellar Solutions', position: 'Executive Assistant' },
  { id: 66, name: 'Nate Morgan', company: 'Nexus Corp', position: 'Software Architect' },
  { id: 67, name: 'Orla Murphy', company: 'Innovate Inc.', position: 'Data Engineer' },
  { id: 68, name: 'Pete Murray', company: 'Future Solutions', position: 'Principal Engineer' },
  { id: 69, name: 'Rose Parker', company: 'Data Dynamics', position: 'Marketing Analyst' },
  { id: 70, name: 'Saul Price', company: 'QuantumLeap Co.', position: 'Head of Product' },
  { id: 71, name: 'Thea Ross', company: 'Innovate Inc.', position: 'Community Manager' },
  { id: 72, name: 'Uma Russell', company: 'Future Solutions', position: 'Full Stack Developer' },
  { id: 73, name: 'Vince Sanders', company: 'Data Dynamics', position: 'Security Analyst' },
  { id: 74, name: 'Willa Scott', company: 'QuantumLeap Co.', position: 'Talent Acquisition' },
  { id: 75, name: 'Alex Stone', company: 'Synergy Systems', position: 'Solutions Engineer' },
  { id: 76, name: 'Brielle Taylor', company: 'Apex Innovations', position: 'Technical Project Manager' },
  { id: 77, name: 'Cody Thompson', company: 'Stellar Solutions', position: 'Help Desk Supervisor' },
  { id: 78, name: 'Daphne Walker', company: 'Nexus Corp', position: 'Risk Analyst' },
  { id: 79, name: 'Ezra Ward', company: 'Synergy Systems', position: 'Systems Integration Specialist' },
  { id: 80, name: 'Faith Watson', company: 'Apex Innovations', position: 'UI Designer' },
  { id: 81, name: 'Gus White', company: 'Stellar Solutions', position: 'Data Center Technician' },
  { id: 82, name: 'Hazel Williams', company: 'Nexus Corp', position: 'Corporate Trainer' },
  { id: 83, name: 'Ike Wilson', company: 'Innovate Inc.', position: 'Automation Engineer' },
  { id: 84, name: 'Joy Wood', company: 'Future Solutions', position: 'Mobile QA Tester' },
  { id: 85, name: 'Kai Wright', company: 'Data Dynamics', position: 'SQL Developer' },
  { id: 86, name: 'Lana Young', company: 'QuantumLeap Co.', position: 'Creative Director' },
  { id: 87, name: 'Max Allen', company: 'Innovate Inc.', position: 'Business Analyst' },
  { id: 88, name: 'Nina Bailey', company: 'Future Solutions', position: 'Cloud Administrator' },
  { id: 89, name: 'Omar Barnes', company: 'Data Dynamics', position: 'Senior Data Analyst' },
  { id: 90, name: 'Pia Collins', company: 'QuantumLeap Co.', position: 'UX Researcher' },
  { id: 91, name: 'Rex Cox', company: 'Synergy Systems', position: 'Network Architect' },
  { id: 92, name: 'Sia Edwards', company: 'Apex Innovations', position: 'Digital Strategist' },
  { id: 93, name: 'Tate Fisher', company: 'Stellar Solutions', position: 'Firmware Engineer' },
  { id: 94, name: 'Vera Gibson', company: 'Nexus Corp', position: 'Content Manager' },
  { id: 95, name: 'Wes Grant', company: 'Synergy Systems', position: 'Database Specialist' },
  { id: 96, name: 'Zara Hayes', company: 'Apex Innovations', position: 'Marketing Operations' },
  { id: 97, name: 'Abel Henderson', company: 'Stellar Solutions', position: 'Product Marketing Manager' },
  { id: 98, name: 'Bria Hicks', company: 'Nexus Corp', position: 'Internal Auditor' },
  { id: 99, name: 'Cian Hill', company: 'Innovate Inc.', position: 'Senior Systems Engineer' },
  { id: 100, name: 'Dina Howard', company: 'Future Solutions', position: 'IT Project Manager' }
];
